export const API = {
  AUTH: {
    LOGIN: "/api/auth/login",
    REGISTER: "/api/auth/register",
    FORGOT_PASSWORD: "/api/auth/forgot-password",
    RESET_PASSWORD: "/api/auth/reset-password",
    WHOAMI: "/api/auth/whoami",
    UPDATE_PROFILE: "/api/auth/update-profile",
    UPDATE_BY_ID: (id: string) => `/api/auth/${id}`,
  },
  ADMIN: {
    USERS: "/api/admin/users",
    USER_BY_ID: (id: string) => `/api/admin/users/${id}`,
    MOVIES: "/api/admin/movies",
    MOVIE_BY_ID: (id: string) => `/api/admin/movies/${id}`,
    HALLS: "/api/admin/halls",
    HALL_BY_ID: (id: string) => `/api/admin/halls/${id}`,
    SHOWTIMES: "/api/admin/showtimes",
    SHOWTIME_BY_ID: (id: string) => `/api/admin/showtimes/${id}`,
    SALES_SUMMARY: "/api/admin/sales/summary",
    LOYALTY_USERS: "/api/admin/loyalty/users",
    LOYALTY_USER_BY_ID: (id: string) => `/api/admin/loyalty/users/${id}`,
    LOYALTY_ADJUST: "/api/admin/loyalty/adjust",
    REWARDS: "/api/admin/rewards",
    REWARD_BY_ID: (id: string) => `/api/admin/rewards/${id}`,
  },
  MOVIES: "/api/movies",
  MOVIE_BY_ID: (id: string) => `/api/movies/${id}`,
} as const;

